#!/usr/bin/env bash
# run with sudo

if [ $EUID -ne 0 ] ; then
    clear
    echo ""
    echo " Ubuntu Workstation LTS script must be run as root. Now I will just exit..." 1>&2
    echo ""
    sleep 2
    exit 1
fi

# Remove remaining oneconf, note, also removes software-center which you may not want
apt-get --purge -y autoremove oneconf oneconf-common python-ubuntu-sso-client ubuntu-sso-client ubuntu-sso-client-qt ubuntuone-client ubuntuone-client-data

# Remove account plugins that are privacy/etc. risks
apt-get --purge -y autoremove account-plugin-aim account-plugin-facebook account-plugin-flickr account-plugin-google account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo folks-common friends friends-dispatcher friends-facebook friends-twitter gnome-contacts nautilus-sendto unity-lens-friends unity-scope-gdrive unity-scope-musicstores unity-scope-zotero libfolks-eds25 libfriends0 mcp-account-manager-uoa rhythmbox-plugin-magnatune libaccount-plugin-google

# Remove more bloatware from desktop
apt-get --purge -y autoremove gnome-accessibility-themes gnome-mines gnome-orca gnome-sudoku gnomine nautilus-sendto-empathy aisleriot  brltty cheese cheese-common example-content unity-plugin-scopes unity-scope-mediascanner2

# Remove unity lens related packages
apt-get --purge -y autoremove telepathy-indicator unity-lens-music unity-lens-photos unity-lens-video unity-scope-audacious unity-scope-chromiumbookmarks unity-scope-clementine unity-scope-colourlovers unity-scope-devhelp unity-scope-firefoxbookmarks unity-scope-gmusicbrowser unity-scope-gourmet unity-scope-guayadeque unity-scope-musique unity-scope-openclipart unity-scope-texdoc unity-scope-tomboy unity-scope-yelp unity-webapps-common unity-webapps-qml unity-webapps-service xul-ext-unity xul-ext-websites-integration unity-scope-video-remote unity-voice-service unity-scope-virtualbox

# Remove local mail clients if you only use webmail
apt-get --purge -y autoremove evolution-data-server* thunderbird*

# Remove Zeitgeist event logger
# NOTE: Disabled as it tries to remove nautilus and gedit that are essential
#apt-get --purge -y autoremove zeitgeist zeitgeist-core zeitgeist-datahub python-zeitgeist rhythmbox-plugin-magnatune rhythmbox-plugin-zeitgeist libzeitgeist-1.0-1 libzeitgeist-2.0-0 
# Cannot remove libzeitgeist without removing nautilus, so remove all of the other components
apt-get --purge -y autoremove zeitgeist zeitgeist-datahub zeitgeist-core python-zeitgeist rhythmbox-plugin-zeitgeist

# Remove ubuntu firefox extension
apt-get --purge -y autoremove xul-ext-ubufox

# Remove telepathy
apt-get --purge -y autoremove telepathy-gabble telepathy-haze telepathy-idle telepathy-logger telepathy-mission-control-5 telepathy-salut

# Remove totem media player
apt-get --purge -y autoremove totem totem-common totem-plugins totem-mozilla

# Remove rhythmbox iTunes Firefox plugin
apt-get --purge -y autoremove rhythmbox-mozilla

# Remove error submission daemon
apt-get --purge -y autoremove whoopsie whoopsie-preferences

# Clear out any packages that are no longer required at this point
apt-get --purge -y autoremove
