#!/usr/bin/env bash
# run with sudo

if [ $EUID -ne 0 ] ; then
    clear
    echo ""
    echo " Ubuntu Workstation LTS script must be run as root. Now I will just exit..." 1>&2
    echo ""
    sleep 2
    exit 1
fi

# Remove remaining oneconf, note, also removes software-center which you may not want
apt-get --purge -y autoremove oneconf oneconf-common python-ubuntu-sso-client ubuntu-sso-client ubuntu-sso-client-qt ubuntuone-client ubuntuone-client-data

# Remove account plugins that are privacy/etc. risks
apt-get --purge -y autoremove account-plugin-aim account-plugin-facebook account-plugin-flickr account-plugin-google account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo folks-common friends friends-dispatcher friends-facebook friends-twitter gnome-contacts nautilus-sendto unity-lens-friends unity-scope-gdrive unity-scope-musicstores unity-scope-zotero libfolks-eds25 libfriends0 mcp-account-manager-uoa rhythmbox-plugin-magnatune libaccount-plugin-google

# Remove unity lens related packages
apt-get --purge -y autoremove telepathy-indicator unity-lens-music unity-lens-photos unity-lens-video unity-scope-audacious unity-scope-chromiumbookmarks unity-scope-clementine unity-scope-colourlovers unity-scope-devhelp unity-scope-firefoxbookmarks unity-scope-gmusicbrowser unity-scope-gourmet unity-scope-guayadeque unity-scope-musique unity-scope-openclipart unity-scope-texdoc unity-scope-tomboy unity-scope-yelp unity-webapps-common unity-webapps-qml unity-webapps-service xul-ext-unity xul-ext-websites-integration unity-scope-video-remote unity-voice-service unity-scope-virtualbox

# Remove local mail clients if you only use webmail
apt-get --purge -y autoremove evolution-data-server* thunderbird*

# Remove Zeitgeist event logger
# NOTE: Disabled as it tries to remove nautilus and gedit that are essential
#apt-get --purge -y autoremove zeitgeist zeitgeist-core zeitgeist-datahub python-zeitgeist rhythmbox-plugin-magnatune rhythmbox-plugin-zeitgeist libzeitgeist-1.0-1 libzeitgeist-2.0-0 
# Cannot remove libzeitgeist without removing nautilus, so remove all of the other components
apt-get --purge -y autoremove zeitgeist zeitgeist-datahub zeitgeist-core python-zeitgeist rhythmbox-plugin-zeitgeist

# Remove ubuntu firefox extension
apt-get --purge -y autoremove xul-ext-ubufox

# Remove telepathy
apt-get --purge -y autoremove telepathy-gabble telepathy-haze telepathy-idle telepathy-logger telepathy-mission-control-5 telepathy-salut

# Remove totem media player
apt-get --purge -y autoremove totem totem-common totem-plugins totem-mozilla

# Remove rhythmbox iTunes Firefox plugin
apt-get --purge -y autoremove rhythmbox-mozilla

# Remove error submission daemon
apt-get --purge -y autoremove whoopsie whoopsie-preferences

# Remove more bloatware
apt-get --purge -y autoremove shotwell shotwell-common landscape-* colord deja-dup deja-dup-backend-gvfs duplicity empathy empathy-common gnome-mahjongg gnome-screensaver gnome-video-effects gnomine libreoffice-* libsane simple-scan hplip* rhythmbox* sane-utils totem* remmina* checkbox* usb-creator* webbrowser-app transmission-* seahorse* bluez bluez-cups

# Clear out any packages that are no longer required at this point
apt-get --purge -y autoremove
apt-get update

# Disable Online suggestions
GS="/usr/bin/gsettings"
CCUL="com.canonical.Unity.lenses"

# Figure out the version of Ubuntu that you're running
V=$(/usr/bin/lsb_release -rs)
# The privacy problems started with v12.10, so earlier versions should do nothing

# Added check because 14.04.1 isn't a number
if [ $V == "14.04.1" ]; then
  $V=14.04
fi

# Minimum version check
MIN=`echo $V'>'12.10 | bc -l`

# Maximum version check
FIXED_VER=15.04
MAX=`echo $FIXED_VER'>'$V | bc -l`

if [[ $MIN -eq 0 || $MAX -eq 0 ]]; then 
  echo "Good news! This version of Ubuntu is not known to invade your privacy."
  exit 0    # The script should exit if Ubuntu version is outside of range
fi

# Check if Canonical schema is present. Take first match, ignoring case.
SCHEMA="$($GS list-schemas | grep -i $CCUL | head -1)"
if [[ -z "$SCHEMA" ]]
  then
  printf "Error: could not find Canonical schema %s.\n" "$CCUL" 1>&2
  exit 1
else
  CCUL="$SCHEMA"
fi

# Turn off "Remote Search", so search terms in Dash aren't sent to the internet
$GS set "$CCUL" remote-content-search none

# If you're using a version earlier than v13.10, uninstall unity-lens-shopping
if [[ $V < 13.10 ]]; then
  sudo apt-get remove -y unity-lens-shopping

# If you're using a later version, disable remote scopes
else
  $GS set "$CCUL" disabled-scopes \
    "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope',
    'more_suggestions-populartracks.scope', 'music-musicstore.scope',
    'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope',
    'more_suggestions-skimlinks.scope']"
fi;

# Block connections to Ubuntu's ad server, just in case
if ! grep -q "127.0.0.1 productsearch.ubuntu.com" /etc/hosts; then
  echo -e "\n127.0.0.1 productsearch.ubuntu.com" | sudo tee -a /etc/hosts >/dev/null
fi
# Editing /etc/hosts is OK, but adding an iptables rule seems to be
# a more elegant solution
sudo iptables -A OUTPUT -d 91.189.92.11 -j REJECT

echo "All done. Enjoy your Workstation."
